#!/usr/bin/env python

import sys

import matplotlib.pyplot as plt

import sim
import duo

if __name__ == '__main__':
    one = sim.load(sys.argv[1])
    two = sim.load(sys.argv[2])

    f, (a1, a2) = plt.subplots(1, 2, sharex=False, sharey=False, figsize = (9, 4))
    (t1, b1, uh1, rh1) = sim.run(one)
    (t2, b2, uh2, rh2) = sim.run(two)
    duo.visualize(a1, one["start"], one["goals"], trajectories=[t1], u_hs=[uh1])
    duo.visualize(a2, two["start"], two["goals"], trajectories=[t2], u_hs=[uh2])
    plt.show()
